In [1]:
import numpy as np
from datetime import date, timedelta

# Create a 3x3x3 array with random values 

In [17]:
arr = np.random.rand(3,3,3)
print(arr)

[[[3.51744361e-01 2.90992428e-01 6.10742322e-02]
  [9.74704298e-01 1.40013355e-01 1.93028260e-01]
  [4.14764584e-01 5.05143212e-01 5.31499373e-01]]

 [[4.05051240e-01 6.95662764e-01 9.94521008e-01]
  [3.85575120e-01 2.47231754e-01 3.55626038e-02]
  [1.69217765e-01 8.53669742e-01 5.27685660e-01]]

 [[5.83975632e-01 3.07775548e-01 1.96617793e-01]
  [3.63980484e-01 6.37513492e-01 3.68912550e-01]
  [2.22933988e-04 2.52789207e-01 5.88526229e-01]]]


# Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [18]:
arr = np.diag(np.arange(4) + 1, k = -1)
print(arr)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# Create a 8x8 matrix and fill it with a checkerboard pattern

In [19]:
arr = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# Normalize a 5x5 random matrix

In [20]:
arr = np.random.random((5,5))
arr = (arr - np.mean (arr)) / (np.std (arr))
print(arr)

[[ 0.18356693 -0.5312192  -1.01956589 -0.74331233 -1.10597109]
 [ 1.38733993  1.50153624  1.01946329 -0.87487517 -1.55642218]
 [ 0.52912593  1.08147132  1.46409442 -1.36289967 -0.84848045]
 [-1.61254016 -0.75092519  0.29656614  0.04972645  0.81954618]
 [-0.72814413  1.184822    0.90976771 -0.06692848  0.7742574 ]]


# How to find common values between two arrays?

In [21]:
arr1 = np.random.randint(0,10,10)
arr2 = np.random.randint(0,10,10)

print(np.intersect1d(arr1, arr2))

[1 3 4 8 9]


# How to get the dates of yesterday, today and tomorrow?

In [23]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print("Yesterday's date:",yesterday,"Today's date:",today,"Tomorrow's date:",tomorrow)

Yesterday's date: 2020-07-28 Today's date: 2020-07-29 Tomorrow's date: 2020-07-30


# Consider two random array A and B, check if they are equal

In [8]:
arr1 = np.random.rand(3,3)
arr2 = np.random.rand(3,3)

equal = np.array_equal(arr1,arr2)
print(f'Array1:\n{arr1}\n\n')
print(f'Array2:\n{arr2}\n\n')
print(f'Equality: {equal}')

Array1:
[[0.46967401 0.86706819 0.06763937]
 [0.44843752 0.17353    0.25375812]
 [0.93272002 0.23752587 0.50145931]]


Array2:
[[0.56269256 0.31152634 0.99719537]
 [0.925039   0.59890311 0.70210409]
 [0.02194227 0.19164747 0.87615293]]


Equality: False


# Create random vector of size 10 and replace the maximum value by 0 

In [24]:
arr = np.random.rand(10)
arr[arr.argmax()] = 0
print(arr)

[0.09634194 0.83174952 0.         0.57511866 0.37441029 0.84168436
 0.39646856 0.29946857 0.66862892 0.37071151]


# How to print all the values of an array?

In [28]:
arr = np.ones((10, 10))
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


# Subtract the mean of each row of a matrix

In [29]:
arr_mean = arr - arr.mean(axis=1, keepdims=True)

print(arr_mean)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


# Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [30]:
arr1 = np.ones(5)
arr2 = np.random.randint(0, len(arr1), 10)
arr1 += np.bincount(arr2, minlength = len(arr1))
print(arr1)

[3. 5. 3. 2. 2.]


# How to get the diagonal of a dot product?

In [32]:
arr1 = np.random.randint(0,10,(3,3))
arr2 = np.random.randint(0,10,(3,3))

np.einsum("ij,ji->i", arr1, arr2)

array([ 37, 104,  55])

# How to find the most frequent value in an array?

In [33]:
arr = np.random.randint(0,10,20)
print(arr)
print(max(set(arr), key = list(arr).count))

[8 1 2 1 8 4 7 3 3 4 2 1 5 0 0 7 9 1 8 1]
1


# How to get the n largest values of an array

In [15]:
arr = np.random.randint(0,10,50)
np.bincount(arr).argmax()

8

# How to create a record array from a regular array?

In [36]:

arr = np.array([("Science", 88.5, 90),
                 ("Maths", 87, 99),
             ("English", 85.5, 91)])

print(arr)
print("\nRECORD ARRAY")
record = np.core.records.fromarrays(arr.T,
                              names='col1, col2, col3',
                              formats = 'S80, f8, i8')
record

[['Science' '88.5' '90']
 ['Maths' '87' '99']
 ['English' '85.5' '91']]

RECORD ARRAY


rec.array([(b'Science', 88.5, 90), (b'Maths', 87. , 99),
           (b'English', 85.5, 91)],
          dtype=[('col1', 'S80'), ('col2', '<f8'), ('col3', '<i8')])